# Generated by Django 4.2.4 on 2023-08-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orderfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_telegram_user', to='users.tguser'),
        ),
    ]
