# Generated by Django 4.2.4 on 2023-09-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0002_alter_food_image_alter_order_lat_alter_order_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='media/media/food_images/'),
        ),
    ]
