# Generated by Django 4.2.5 on 2023-09-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderfood', '0004_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
