# Generated by Django 4.2.4 on 2023-08-29 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_veryfied',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tu_sms', to='users.tguser')),
            ],
        ),
    ]
